### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by hisazumi** [hisazumi/crostest#1]
/usr/bin/ld: CMakeFiles/crostest_node.dir/Generated/DependentCode.cpp.o: relocation R_X86_64_32S against symbol `_ZN7English5Hello27_RTCOP_FinalizePartialClassEv' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [/home/ubuntu/catkin_ws/devel/.private/crostest/lib/crostest/crostest_node] Error 1
make[1]: *** [CMakeFiles/crostest_node.dir/all] Error 2
make: *** [all] Error 2

**Comment by hisazumi** [comment]
自分の環境でlibRTCOP.aを再コンパイルしてみたり、-fPICをつけて再コンパイルしてみても、同じエラーです。

**Comment by lzh610** [comment]
> 自分の環境でlibRTCOP.aを再コンパイルしてみたり、-fPICをつけて再コンパイルしてみても、同じエラーです。

確かにこの前自分の環境でも同じエラーが発生した。調べた資料により、コンパイルする時に-fPICが元のライブラリーに追加されていないと原因とします。
解決方法としては、SET(CMAKE_EXE_LINKER_FLAGS " -no-pie")をcmakefileに追加する。
一度試したのに失敗しました。

**Comment by hisazumi** [comment]
It solved! I have added -no-pie to CFLAGS.
